<a href="https://colab.research.google.com/github/seoyeonmmn/python_basic/blob/main/NLP_with_Pytorch_chapter01_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
# 1. 2D tensor 만들고 dim = 0 위치에 크기가 1인 차원 추가하기
x = torch.rand(2, 2)
print(x)
y = x.unsqueeze(0)
print(y)
print(y.shape)

tensor([[0.4746, 0.6210],
        [0.8460, 0.7731]])
tensor([[[0.4746, 0.6210],
         [0.8460, 0.7731]]])
torch.Size([1, 2, 2])


In [8]:
# 2. 1번에서 추가한 차원 다시 삭제하기
x = y.squeeze()
print(x, x.shape)

tensor([[0.4746, 0.6210],
        [0.8460, 0.7731]]) torch.Size([2, 2])


In [10]:
# 3. 범위가 [3, 7)이고 크기가 5*3인 랜덤한 tensor 만들기

x = torch.rand(5, 3)*4 + 3
print(x)

tensor([[3.1067, 3.3218, 5.8687],
        [5.4366, 3.6463, 6.4593],
        [6.8782, 3.4438, 5.2147],
        [6.4842, 5.4645, 5.2730],
        [5.2186, 4.3478, 3.0851]])


In [11]:
# 4. 정규 분포를 이용하여 tensor 만들기

x = torch.randn(3, 3)
x

tensor([[-0.4315, -0.2049,  0.0113],
        [ 2.3551,  0.7925, -0.6956],
        [-0.3737,  0.1524, -0.5604]])

In [22]:
# 5. torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스 추출

x = torch.Tensor([1, 1, 1, 0, 1])
idx = torch.where(x != 0)
idx


(tensor([0, 1, 2, 4]),)

In [23]:
# 6.크기가 (3, 1)인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓아라.

x = torch.rand(3, 1)

torch.stack([x, x, x, x])

tensor([[[0.4031],
         [0.5708],
         [0.8707]],

        [[0.4031],
         [0.5708],
         [0.8707]],

        [[0.4031],
         [0.5708],
         [0.8707]],

        [[0.4031],
         [0.5708],
         [0.8707]]])

In [29]:
# 7. a = torch.rand(3, 4, 5)와 b = torch.rand(3, 5, 4)의 배치 행렬 곱셈을 계산하라.

a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)

print(torch.matmul(a, b))
print(torch.bmm(a, b))

tensor([[[1.7651, 2.1742, 1.8313, 2.0341],
         [1.1651, 1.2302, 0.9644, 1.0809],
         [1.8836, 2.3267, 1.9343, 2.1478],
         [1.8762, 2.4171, 2.1661, 1.6392]],

        [[1.0057, 0.8921, 0.7903, 0.7320],
         [1.1135, 0.7688, 0.7550, 1.1359],
         [0.6146, 0.8164, 0.5005, 0.6198],
         [1.0952, 1.0019, 1.1429, 1.3197]],

        [[1.2529, 1.1164, 2.1972, 1.2700],
         [1.1355, 0.7669, 1.5231, 1.1452],
         [0.3505, 0.3706, 0.7793, 0.4520],
         [1.4326, 1.0111, 2.1144, 1.2383]]])
tensor([[[1.7651, 2.1742, 1.8313, 2.0341],
         [1.1651, 1.2302, 0.9644, 1.0809],
         [1.8836, 2.3267, 1.9343, 2.1478],
         [1.8762, 2.4171, 2.1661, 1.6392]],

        [[1.0057, 0.8921, 0.7903, 0.7320],
         [1.1135, 0.7688, 0.7550, 1.1359],
         [0.6146, 0.8164, 0.5005, 0.6198],
         [1.0952, 1.0019, 1.1429, 1.3197]],

        [[1.2529, 1.1164, 2.1972, 1.2700],
         [1.1355, 0.7669, 1.5231, 1.1452],
         [0.3505, 0.3706, 0.7793, 0.4520],
 

In [33]:
# 8. a = torch.rand(3, 4, 5)와 b = torch.rand(5, 4)
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)

print(torch.matmul(a, b))
print(torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())))

tensor([[[0.9156, 0.9876, 1.1598, 0.2869],
         [1.3052, 1.4308, 1.0805, 0.5676],
         [1.1677, 1.1900, 1.2321, 0.5814],
         [0.9991, 0.8775, 1.1643, 0.4763]],

        [[1.6384, 1.6536, 1.5182, 0.9881],
         [0.8425, 0.8483, 0.8950, 0.5406],
         [1.1286, 1.3814, 0.5908, 0.6497],
         [1.1318, 1.1969, 1.2433, 0.3641]],

        [[1.0222, 0.8349, 1.0383, 0.7226],
         [1.3668, 1.4400, 1.3463, 0.7016],
         [0.7921, 0.8960, 0.8320, 0.3704],
         [0.8989, 0.9381, 0.7128, 0.5157]]])
tensor([[[0.9156, 0.9876, 1.1598, 0.2869],
         [1.3052, 1.4308, 1.0805, 0.5676],
         [1.1677, 1.1900, 1.2321, 0.5814],
         [0.9991, 0.8775, 1.1643, 0.4763]],

        [[1.6384, 1.6536, 1.5182, 0.9881],
         [0.8425, 0.8483, 0.8950, 0.5406],
         [1.1286, 1.3814, 0.5908, 0.6497],
         [1.1318, 1.1969, 1.2433, 0.3641]],

        [[1.0222, 0.8349, 1.0383, 0.7226],
         [1.3668, 1.4400, 1.3463, 0.7016],
         [0.7921, 0.8960, 0.8320, 0.3704],
 