In [ ]:
# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.20.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [17]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [18]:
# Size of the array
print(arr.size)
# Memory size of one array element in bytes
print("Memory size of one array element in bytes: ", arr.itemsize)
# Memory size of numpy array in bytes
print("memory size of numpy array in bytes: ", arr.itemsize*arr.size)

10
Memory size of one array element in bytes:  8
memory size of numpy array in bytes:  80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [35]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
arr_rev = np.flip(arr)
arr_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
arr = np.arange(0, 9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [37]:
arr = np.array([1, 2, 0, 0, 4, 0])
idx = np.where(arr!=0)
idx

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
arr = np.eye(3, 3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [34]:
arr = np.random.rand(3, 3, 3)
arr

array([[[0.28777534, 0.13002857, 0.01936696],
        [0.67883553, 0.21162812, 0.26554666],
        [0.49157316, 0.05336255, 0.57411761]],

       [[0.14672857, 0.58930554, 0.69975836],
        [0.10233443, 0.41405599, 0.69440016],
        [0.41417927, 0.04995346, 0.53589641]],

       [[0.66379465, 0.51488911, 0.94459476],
        [0.58655504, 0.90340192, 0.1374747 ],
        [0.13927635, 0.80739129, 0.39767684]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
arr = np.random.randint(low = 0, high = 100, size = (10, 10))
max = np.max(arr)
min = np.min(arr)


arr, max, min

(array([[15, 25, 53, 84, 58, 85, 29, 44, 37, 22],
        [91, 54, 76, 12, 59, 26, 76, 71, 87, 39],
        [43, 76, 38, 91, 69, 98, 33, 43, 26, 56],
        [69, 73, 52, 89, 27, 43,  1, 82, 94, 96],
        [26, 84, 30, 64, 22, 98, 52,  3, 70, 12],
        [39, 83, 48, 61, 70, 13, 36, 23, 22, 66],
        [92, 95, 53,  9, 41, 57, 88, 93, 76, 82],
        [11, 36, 16, 30, 84, 57, 35, 41, 81,  2],
        [85, 93, 36, 46, 80, 27, 72, 28,  2, 99],
        [13, 41, 36, 40, 18, 97, 38, 63, 46, 89]]),
 99,
 1)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [50]:
arr = np.random.randint(low = 0, high = 50 , size = 30)
arr, arr.mean()

(array([37,  2, 34, 28, 14, 11, 42, 26, 40, 21, 16, 28, 37, 41, 45, 40, 42,
        11, 22,  6, 32, 14, 36, 23, 11, 35, 32, 46, 27, 49]),
 28.266666666666666)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [62]:
m = int(input("Height of the array: \n"))
n = int(input("Width of the array: \n"))

arr = np.zeros([m, n])

for i in range(m):
    for j in range(n):
        if (i == 0) or (j == 0) or (i == m-1) or (j == n-1):
            arr[i][j] = 1
        else:
            arr[i][j] = 0

arr

Height of the array: 
4
Width of the array: 
3


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [76]:
row1 = np.insert(arr, 0, 0, axis = 0)
row2 = np.insert(row1, m+1, 0, axis = 0)
col1 = np.insert(row2, 0, 0, axis = 1)
col2 = np.insert(col1, n+1, 0, axis = 1)

arr_bor0 = col2
print(arr_bor0)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [83]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [82]:
arr = np.zeros([5, 5])

for i in range(5):
    for j in range(5):
        if (i - j) == 1:
            arr[i][j] = i

arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [80]:
arr = np.ones([8, 8])

for i in range (0, 8):
    for j in range(0, 8):
        if (i + j)%2 == 0:
            arr[i][j] = 0
            
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [93]:
max = 6*7*8
arr = np.arange(1, max+1).reshape([6, 7, 8])

i, j, k = np.where(arr == 100)
print('the index of the 100th element: ', i, j, k)

the index of the 100th element:  [1] [5] [3]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [85]:
mat = np.array([[0, 1],
               [1, 0]])

#np.tile(arr, repetitions)
arr = np.tile(mat, (4, 4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [94]:
arr = np.random.normal(0, 1, [5, 5])  # parameter -> (mean, std, size)
print(arr)

[[ 0.3743189  -1.84955116 -0.27810508  0.31784693 -0.35876103]
 [-0.04193944  1.25794105  0.62834995 -1.00292632  0.78797796]
 [-1.05711954  0.54215727  0.91940949  0.05073418  1.20135336]
 [-0.08601853 -0.14813658  0.13912627 -1.90290863  2.33014207]
 [-0.30626553 -1.45606357 -2.07490519 -0.24545321  0.002979  ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [109]:
color = np.dtype([("r", np.ubyte),     #ubyte : unsigned bytes (0~255)
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
                  
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [108]:
# 1
np.random.seed(1)
arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

print(np.dot(arr1, arr2))

# 2
np.random.seed(1)
arr1 = np.random.randint(low = -10, high = 50, size = 15).reshape([5, 3])
arr2 = np.random.randint(low = -10, high = 50, size = 6).reshape([3, 2])

print(arr1)
print(arr2)
print(np.dot(arr1, arr2))

[[0.68206033 0.27524102]
 [0.3029876  0.22070707]
 [0.39654291 0.44394889]
 [0.73120183 0.83238604]
 [0.63309939 0.23052559]]
[[ 27  33   2]
 [ -2  -1   1]
 [ -5   5 -10]
 [  6  -9   2]
 [ -3  35  -4]]
[[15 40]
 [10 27]
 [ 8 10]]
[[ 751 1991]
 [ -32  -97]
 [-105 -165]
 [  16   17]
 [ 273  785]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [147]:
arr = np.random.randint(low = 0, high = 10, size = 20)

for i in range(20):
    if 3 <= arr[i] <= 8:
        arr[i] = 0
        
arr = np.delete(arr, np.where(arr == 0))
arr

array([9, 9, 2])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [99]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [126]:
Z = np.array([1, 2, 3, 4])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([False, False, False, False])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [150]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [129]:
arr = np.random.rand(5, 5)
print(arr)
arr = np.round(arr)
print(arr)

[[0.83462567 0.01828828 0.75014431 0.98886109 0.74816565]
 [0.28044399 0.78927933 0.10322601 0.44789353 0.9085955 ]
 [0.29361415 0.28777534 0.13002857 0.01936696 0.67883553]
 [0.21162812 0.26554666 0.49157316 0.05336255 0.57411761]
 [0.14672857 0.58930554 0.69975836 0.10233443 0.41405599]]
[[1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [160]:
arr1 = np.random.randint(low = 0, high = 5, size = 10)
arr2 = np.random.randint(low = 0, high = 5, size = 10)
print(arr1, arr2)
lst1 = []
lst2 = []

for i in arr1:
    for j in arr2:
        if i == j:
            lst1.append(i)

for k in lst1:
    if k not in lst2:
        lst2.append(k)
        
arr = np.array(lst2)
print("Common Values betweet array1 and array2: ", arr)

[4 3 4 3 3 4 0 3 1 4] [4 3 2 2 2 2 2 0 2 1]
Common Values betweet array1 and array2:  [4 3 0 1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)