In [2]:
import numpy as np

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

np.bincount(): non-negative int로 구성된 ndarray에서 빈도수 counting method. 
```
arr = [3, 2, 2, 6, 7, 4, 8, 9, 9, 9]
np.bincount(arr)
```

result => [0 0 2 1 1 0 1 1 1 3] (0:0번 1:0번, 2:2번 3:1번...)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [3]:
I = [2, 4, 6, 8]
np.bincount(I)

array([0, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

In [6]:
X = [0, 0]
I = [1, 1]
np.bincount(I, X)

array([0., 0.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [54]:
arr = np.random.randint(0, 3, (2, 2, 2, 2))
arr

array([[[[1, 2],
         [1, 1]],

        [[1, 2],
         [2, 2]]],


       [[[0, 2],
         [2, 1]],

        [[2, 2],
         [0, 1]]]])

In [53]:
cumsum = arr.cumsum(axis = -1).cumsum(axis = -2)
total = cumsum[-1][-2][-1][-1] + cumsum[-1][-1][-1][-1]
total 

27

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [9]:
A = np.random.randint(0, 10, (5, 5))
B = np.random.randint(0, 10, (5, 5))
print(A, B)

[[9 5 7 8 6]
 [5 6 8 8 0]
 [4 7 9 1 8]
 [4 5 3 3 9]
 [8 3 7 4 4]] [[4 2 4 3 8]
 [7 8 8 5 6]
 [9 0 3 4 0]
 [3 1 9 4 0]
 [1 7 9 7 0]]


In [10]:
print(np.dot(A, B))
print(np.diag(np.dot(A, B)))

[[164 108 223 154 102]
 [158  66 164 109  76]
 [157 121 180 143  74]
 [ 96 114 173 124  62]
 [132  72 149 111  82]]
[164  66 180 124  82]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [20]:
arr = [1, 2, 3, 4, 5]
zeros = np.zeros(1, dtype = np.int32)
result = []

for i in range(5):
    result.append(arr[i])
    result.append(zeros[0])
    result.append(zeros[0])
    result.append(zeros[0])
    
result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [59]:
A = np.random.randint(0, 5, (5, 5, 3))
B = np.random.randint(0, 5, (5, 5))
A, B

(array([[[1, 1, 0],
         [0, 3, 3],
         [2, 0, 1],
         [2, 3, 3],
         [4, 4, 3]],
 
        [[0, 3, 3],
         [2, 2, 4],
         [2, 3, 3],
         [3, 2, 1],
         [1, 0, 3]],
 
        [[4, 4, 4],
         [1, 1, 1],
         [2, 4, 1],
         [3, 2, 4],
         [0, 2, 4]],
 
        [[2, 2, 0],
         [1, 3, 0],
         [2, 3, 3],
         [1, 2, 3],
         [2, 0, 0]],
 
        [[4, 1, 2],
         [0, 1, 1],
         [1, 1, 1],
         [2, 3, 2],
         [2, 1, 3]]]),
 array([[2, 4, 4, 4, 2],
        [1, 0, 1, 1, 4],
        [4, 4, 1, 3, 3],
        [1, 4, 3, 0, 2],
        [4, 3, 2, 1, 4]]))

In [61]:
B[:, :, None]

array([[[2],
        [4],
        [4],
        [4],
        [2]],

       [[1],
        [0],
        [1],
        [1],
        [4]],

       [[4],
        [4],
        [1],
        [3],
        [3]],

       [[1],
        [4],
        [3],
        [0],
        [2]],

       [[4],
        [3],
        [2],
        [1],
        [4]]])

In [60]:
A*B[:, :, None]

array([[[ 2,  2,  0],
        [ 0, 12, 12],
        [ 8,  0,  4],
        [ 8, 12, 12],
        [ 8,  8,  6]],

       [[ 0,  3,  3],
        [ 0,  0,  0],
        [ 2,  3,  3],
        [ 3,  2,  1],
        [ 4,  0, 12]],

       [[16, 16, 16],
        [ 4,  4,  4],
        [ 2,  4,  1],
        [ 9,  6, 12],
        [ 0,  6, 12]],

       [[ 2,  2,  0],
        [ 4, 12,  0],
        [ 6,  9,  9],
        [ 0,  0,  0],
        [ 4,  0,  0]],

       [[16,  4,  8],
        [ 0,  3,  3],
        [ 2,  2,  2],
        [ 2,  3,  2],
        [ 8,  4, 12]]])

#### 72. How to swap two rows of an array? (★★★)

In [80]:
# sol1)
def swap(arr, i, j):
    extra = np.zeros_like(arr)
    extra[i][:] = arr[i][:]

    arr[i][:] = arr[j][:]

    arr[j][:] = extra[i][:]
    return arr

In [81]:
arr = np.random.randint(0, 5, (3, 3))
arr

array([[0, 2, 1],
       [2, 4, 1],
       [1, 4, 1]])

In [82]:
swap(arr, 0, 1)

array([[2, 4, 1],
       [0, 2, 1],
       [1, 4, 1]])

In [83]:
# sol2)

def swap(arr, i, j):
    arr[[i, j]] = arr[[j, i]]
    return arr

In [85]:
A = np.arange(9).reshape(3, 3)
swap(A, 0, 1)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [86]:
A = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]
C = np.bincount(A)
C, np.sort(C)

(array([1, 2, 3, 4], dtype=int64), array([1, 2, 3, 4], dtype=int64))

#### 75. How to compute averages using a sliding window over an array? (★★★)

**Sliding Window Algorithm**  
일정한 범위를 유지하면서 이동하는 window.
window 내에 있는 데이터 이용하여 문제 풀이

In [94]:
size = 4  # window size
n = 10 # array size
arr = np.random.randint(1, 10, n)
average = []

print(arr)
for i in range(n-size+1):
    average.append(np.mean(arr[i:i+size]))
    
print(average)

[3 8 9 1 4 6 8 2 3 4]
[5.25, 5.5, 5.0, 4.75, 5.0, 4.75, 4.25]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [96]:
Z = np.arange(9)
arr = Z.reshape(3, -1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [67]:
A = np.random.randint(0, 2, 10)
print(A)
np.logical_not(A, out=A)
print(A)

[1 0 0 0 0 0 0 1 1 1]
[0 1 1 1 1 1 1 0 0 0]


In [68]:
B = np.random.uniform(-1.0, 1.0, 10)
print(B)
np.negative(B, out=B)
print(B)

[ 0.42470988 -0.46370096  0.37313203  0.66180545 -0.97271097 -0.32607205
  0.16900922  0.47159215 -0.87162893  0.5534545 ]
[-0.42470988  0.46370096 -0.37313203 -0.66180545  0.97271097  0.32607205
 -0.16900922 -0.47159215  0.87162893 -0.5534545 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [101]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]

R = []
for i in range(11):
    R.append(Z[i:i+4])
R

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

#### 82. Compute a matrix rank (★★★)


In [102]:
arr = np.random.randint(-5, 5, (3, 3))
arr

array([[ 3,  2, -3],
       [-1, -1,  3],
       [-4, -5, -2]])

In [103]:
np.linalg.matrix_rank(arr)

3

#### 83. How to find the most frequent value in an array?

In [113]:
arr = np.random.randint(0, 5, 20)
arr

array([1, 0, 3, 4, 0, 0, 3, 4, 2, 1, 1, 1, 3, 1, 4, 3, 2, 3, 2, 2])

In [114]:
arr[arr.argmax()]

4

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [115]:
arr = np.arange(100).reshape(10, 10)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [63]:
class Array:
    def __init__(self, n):
        self.array = np.random.randint(0, 10, (n, n))

In [64]:
class Symmetry(Array):
    def __init__(self, n):
        super(Symmetry, self).__init__(n)
#         print(self.array)
        self.array = np.triu(self.array)
#         print(self.array)
        self.symmetry = self.array + self.array.T - np.diag(self.array.diagonal())
        print(self.symmetry)

In [65]:
arr1 = Symmetry(3)
arr2 = Symmetry(5)

[[2 4 1]
 [4 3 7]
 [1 7 7]]
[[7 5 2 4 3]
 [5 3 6 2 4]
 [2 6 6 0 4]
 [4 2 0 7 4]
 [3 4 4 4 1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [103]:
arr = np.random.randint(0, 5, (16, 16))
print(arr)
block = []

for i in range(13):
    for j in range(13):
        block.append(np.sum(arr[i:i+4, j:j+4]))
        
block = np.array(block).reshape(13, 13)
print(block) 

[[1 0 4 3 2 0 3 2 3 3 3 0 1 1 1 0]
 [3 3 3 0 2 2 4 0 0 0 2 0 0 2 0 4]
 [2 2 1 1 2 4 3 3 3 2 3 2 4 3 1 4]
 [0 2 2 4 1 0 4 0 1 3 3 1 0 3 3 1]
 [3 0 0 4 2 1 1 2 0 4 2 4 3 3 2 2]
 [3 3 1 2 0 2 1 4 4 3 4 1 0 2 3 4]
 [0 0 0 4 4 4 4 4 3 0 3 0 0 0 3 4]
 [1 0 2 1 0 0 0 1 2 1 3 2 4 1 4 2]
 [0 0 0 3 3 0 3 3 0 0 2 3 0 0 2 4]
 [2 4 4 3 2 2 0 2 3 4 2 1 3 4 2 1]
 [2 3 4 1 4 2 1 3 4 2 1 4 4 2 4 2]
 [3 3 4 4 3 2 4 0 2 4 3 4 1 4 3 3]
 [2 1 3 1 0 0 2 1 2 4 4 4 1 1 3 4]
 [0 2 2 3 4 1 0 2 1 2 3 4 1 4 0 3]
 [0 4 0 4 2 1 3 0 3 1 3 0 1 2 2 2]
 [3 4 2 4 2 2 1 3 1 3 0 0 0 0 2 2]]
[[31 32 31 35 32 32 34 31 29 27 28 22 28]
 [30 29 29 35 31 28 30 28 30 33 35 31 35]
 [30 27 27 32 30 33 38 41 40 39 38 35 38]
 [28 29 31 38 34 35 38 40 36 31 29 28 33]
 [24 23 27 30 30 33 34 40 36 34 32 32 37]
 [20 23 26 31 33 35 33 37 31 26 25 25 33]
 [24 30 32 33 32 31 30 33 29 28 28 29 34]
 [30 34 31 25 26 26 29 33 34 36 36 40 39]
 [40 45 41 37 34 31 35 35 39 38 38 41 39]
 [44 44 39 31 28 30 38 41 48 46 43 45 42]
 [38 42 38 32 29 27

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [107]:
n = 6

arr = np.random.randint(-100, 100, 10)
print(arr)
print(arr[np.argsort(arr)])
print(arr[np.argsort(arr)][-n])

[-74  75 -20  -9 -63 -91  69 -67  64  65]
[-91 -74 -67 -63 -20  -9  64  65  69  75]
-20


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [160]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [162]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

**np.newaxis**   
numpy array의 차원 늘려줌.

In [163]:
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [112]:
arr = np.random.randint(0, 5, (10, 3))
rows = []
for i in range(10):
    if (arr[i, 0] == arr[i, 1])|(arr[i, 0] == arr[i, 2])|(arr[i, 1] == arr[i, 2]):
        rows.append(i)
print(arr)

print('Rows with unequal values: ')
for i in rows:
    print(arr[i, :])

[[0 3 3]
 [4 0 4]
 [2 3 2]
 [3 3 0]
 [2 2 1]
 [2 0 0]
 [4 2 1]
 [0 1 0]
 [0 1 3]
 [1 4 4]]
Rows with unequal values: 
[0 3 3]
[4 0 4]
[2 3 2]
[3 3 0]
[2 2 1]
[2 0 0]
[0 1 0]
[1 4 4]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

**np.binary_repr(num, width=None)**   
십진수를 이진수로 변환하여 출력하는 함수.   
num = 변환할 십진수, width = 표현할 비트 수   
**np.packbits(a, axis=None)**   
ndarray의 이진수 원소를 np.unit16의 십진수로 변환하는 함수.    
a = 변환할 배열
**np.unpackbits(a, axis=None, count)**   
십진수를 이진수로 반환하는 함수

In [155]:
arr = np.random.randint(0, 10, (3, 3))
arr = arr.astype(np.uint8)
arr

array([[3, 7, 5],
       [5, 0, 1],
       [5, 9, 3]], dtype=uint8)

In [158]:
np.unpackbits(arr[:, np.newaxis], axis = 1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 1],
        [1, 1, 0],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [0, 0, 0],
        [1, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [115]:
arr = np.random.randint(0, 2, (3, 3))
print(arr)
print(np.unique(arr, axis = 0))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

**numpy.einsum(subscripts)**   
'ii': 대각선을 의미   
np.einsum('ii', arr) -> 행렬의 대각합    
np.einsum('ii->i', arr) -> arr의 대각성분을 취하여 이를 ith 성분으로 가지는 벡터 생성   
np.einsum('ij->i', arr) -> arr의 ij번째 원소의 합을 ith 성분으로 가지는 벡터 생성, np.sum(arr, axis = 1)과 동일한 결과   
np.einsum('ji', arr) = np.einsum('ij'->'ji') -> 전치행렬   
np.einsum('i, i', b, b) -> 내적
np.einsum('ij, j', a, b) -> 행렬 a의 ij번째 요소와 행렬 b의 j번째 요소 곱한 뒤 더하기   

In [117]:
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
A, B

(array([1, 4, 5, 2, 7]), array([2, 3, 7, 4, 8]))

In [119]:
#inner product
np.einsum('i, i', A, B), np.dot(A, B)

(113, 113)

In [124]:
#outer product
np.einsum('i, j->ij', A, B)

array([[ 2,  3,  7,  4,  8],
       [ 8, 12, 28, 16, 32],
       [10, 15, 35, 20, 40],
       [ 4,  6, 14,  8, 16],
       [14, 21, 49, 28, 56]])

In [133]:
# sum
np.einsum('i->', A)

19

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [136]:
np.random.seed(0)
X = np.random.randint(0, 5, 3)
Y = np.random.randint(0, 5, 3)
X, Y 

(array([4, 0, 3]), array([3, 3, 1]))

In [138]:
dis = np.sqrt(np.sum(np.square(X-Y)))
dis 

3.7416573867739413

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [159]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
mean = X[idx].mean(axis = 1)
confi = np.percentile(mean, [2.5, 97.5])
confi

array([-0.03883451,  0.34090253])